timezone: Bogota
database:
  :name: ninja-bot
  :host: flame.mongohq.com
  :port: 27042
  :user: your user
  :password: your pass

network:
  :server: irc.freenode.net
  :nick: "NinjaBot"
  :max_messages: 1
  :channels:
  - name: "#cinch-bots"
    timezone: EST
    shapado_site: http://shapado.com
  :port: 6667
  :realname: "http://github.com/dev_co/ninja-bot"
  :verbose: true
  :version: "NinjaBot v3.0"

